// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package configtesting

import (
	"oss-sdk-go/config"
	svcExternal "oss-sdk-go/service/internal/s3shared/config"
)

// UseARNRegionProvider Assertions
var (
	_ svcExternal.UseARNRegionProvider = &config.EnvConfig{}
	_ svcExternal.UseARNRegionProvider = &config.SharedConfig{}
)
