FROM golang:1.15

ENV GOPROXY=direct

ADD . /go/src/oss-sdk-go

RUN apt-get update && apt-get install -y --no-install-recommends \
		vim \
	&& rm -rf /var/list/apt/lists/*

WORKDIR /go/src/oss-sdk-go
CMD ["make", "unit"]
