// Code generated by oss-sdk-go/internal/codegen/cmd/defaultsconfig. DO NOT EDIT.

package defaults

import (
	"fmt"
	"oss-sdk-go/oss"
	"time"
)

// v1TestResolver returns the default Configuration descriptor for the given mode.
//
// Supports the following modes: cross-region, in-region, mobile, standard
func v1TestResolver(mode oss.DefaultsMode) (Configuration, error) {
	var mv oss.DefaultsMode
	mv.SetFromString(string(mode))

	switch mv {
	case oss.DefaultsModeCrossRegion:
		settings := Configuration{
			ConnectTimeout:        oss.Duration(2800 * time.Millisecond),
			RetryMode:             oss.RetryMode("standard"),
			TLSNegotiationTimeout: oss.Duration(2800 * time.Millisecond),
		}
		return settings, nil
	case oss.DefaultsModeInRegion:
		settings := Configuration{
			ConnectTimeout:        oss.Duration(1000 * time.Millisecond),
			RetryMode:             oss.RetryMode("standard"),
			TLSNegotiationTimeout: oss.Duration(1000 * time.Millisecond),
		}
		return settings, nil
	case oss.DefaultsModeMobile:
		settings := Configuration{
			ConnectTimeout:        oss.Duration(10000 * time.Millisecond),
			RetryMode:             oss.RetryMode("adaptive"),
			TLSNegotiationTimeout: oss.Duration(11000 * time.Millisecond),
		}
		return settings, nil
	case oss.DefaultsModeStandard:
		settings := Configuration{
			ConnectTimeout:        oss.Duration(2000 * time.Millisecond),
			RetryMode:             oss.RetryMode("standard"),
			TLSNegotiationTimeout: oss.Duration(2000 * time.Millisecond),
		}
		return settings, nil
	default:
		return Configuration{}, fmt.Errorf("unsupported defaults mode: %v", mode)
	}
}
